Document: screenconfig
Title: Debian screenconfig Manual
Author: <insert document author here>
Abstract: This manual describes what screenconfig is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/screenconfig/screenconfig.sgml.gz

Format: postscript
Files: /usr/share/doc/screenconfig/screenconfig.ps.gz

Format: text
Files: /usr/share/doc/screenconfig/screenconfig.text.gz

Format: HTML
Index: /usr/share/doc/screenconfig/html/index.html
Files: /usr/share/doc/screenconfig/html/*.html
